
package org.example.agence.ws.hotelconsultation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelConsultationServiceImplService", targetNamespace = "http://service.hotelservice.web_services.example.org/", wsdlLocation = "http://localhost:8081/ws/hotelConsultation?wsdl")
public class HotelConsultationServiceImplService
    extends Service
{

    private final static URL HOTELCONSULTATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOTELCONSULTATIONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName HOTELCONSULTATIONSERVICEIMPLSERVICE_QNAME = new QName("http://service.hotelservice.web_services.example.org/", "HotelConsultationServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ws/hotelConsultation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELCONSULTATIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        HOTELCONSULTATIONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public HotelConsultationServiceImplService() {
        super(__getWsdlLocation(), HOTELCONSULTATIONSERVICEIMPLSERVICE_QNAME);
    }

    public HotelConsultationServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELCONSULTATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public HotelConsultationServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, HOTELCONSULTATIONSERVICEIMPLSERVICE_QNAME);
    }

    public HotelConsultationServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELCONSULTATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public HotelConsultationServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelConsultationServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HotelConsultationService
     */
    @WebEndpoint(name = "HotelConsultationServiceImplPort")
    public HotelConsultationService getHotelConsultationServiceImplPort() {
        return super.getPort(new QName("http://service.hotelservice.web_services.example.org/", "HotelConsultationServiceImplPort"), HotelConsultationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelConsultationService
     */
    @WebEndpoint(name = "HotelConsultationServiceImplPort")
    public HotelConsultationService getHotelConsultationServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.hotelservice.web_services.example.org/", "HotelConsultationServiceImplPort"), HotelConsultationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELCONSULTATIONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw HOTELCONSULTATIONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return HOTELCONSULTATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
