
package org.example.agence.ws.hotelconsultation;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelConsultationService", targetNamespace = "http://service.hotelservice.web_services.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelConsultationService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<org.example.agenceservice.ws.hotelconsultation.ChambreDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consulterDisponibilites", targetNamespace = "http://service.hotelservice.web_services.example.org/", className = "org.example.agenceservice.ws.hotelconsultation.ConsulterDisponibilites")
    @ResponseWrapper(localName = "consulterDisponibilitesResponse", targetNamespace = "http://service.hotelservice.web_services.example.org/", className = "org.example.agenceservice.ws.hotelconsultation.ConsulterDisponibilitesResponse")
    @Action(input = "http://service.hotelservice.web_services.example.org/HotelConsultationService/consulterDisponibilitesRequest", output = "http://service.hotelservice.web_services.example.org/HotelConsultationService/consulterDisponibilitesResponse")
    public List<ChambreDTO> consulterDisponibilites(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authentifierAgence", targetNamespace = "http://service.hotelservice.web_services.example.org/", className = "org.example.agenceservice.ws.hotelconsultation.AuthentifierAgence")
    @ResponseWrapper(localName = "authentifierAgenceResponse", targetNamespace = "http://service.hotelservice.web_services.example.org/", className = "org.example.agenceservice.ws.hotelconsultation.AuthentifierAgenceResponse")
    @Action(input = "http://service.hotelservice.web_services.example.org/HotelConsultationService/authentifierAgenceRequest", output = "http://service.hotelservice.web_services.example.org/HotelConsultationService/authentifierAgenceResponse")
    public boolean authentifierAgence(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
